service: alexa-sls-test-azure-functions

provider:
  name: azure
  location: West US

plugins:
  - serverless-azure-functions

package:
  include:
    - ../sharedApp.js

functions:
  alexa:
    handler: handler.alexa
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
