service: alexa-sls-test-gcf

provider:
  name: google
  runtime: nodejs
  project: my-test-project
  credentials: ~/.gcloud/key.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
  include:
    - ../sharedApp.js

functions:
  alexa:
    handler: alexa
    events:
      - http: path