service: alexa-sls-test-gcf

provider:
  name: google
  runtime: nodejs
  project: kb-tests
  credentials: ~/.gcloud/key.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
  include:
    - ../sharedApp.js

functions:
  alexa:
    handler: alexa
    events:
      - http: path